### ISSUE TITLE
tts支持合约的状态信息推送接口onRtnInstrumentStatus()吗？

### ISSUE THREAD

**Issue by hxxjava** [krenx1983/openctp#11]
我是vnpy会员，从TtsTdApi的C++源代码可以找到onRtnInstrumentStatus这个库函数接口的，于是我在tts网关的TtsTdApi增加onRtnInstrumentStatus来输出合约的状态信息，可是我发现连接tts网关成功后并没有收到任何一个合约的状态信息。
难道tts不支持这个接口吗？

**Comment by krenx1983** [comment]
目前不支持，这个函数不会有触发的
