### ISSUE TITLE
SubscribeMarketData

### ISSUE THREAD

**Issue by wellzero** [krenx1983/openctp#12]
Removed

**Comment by luozero** [comment]
在ubtuntu上有人用过openctp吗，对了一个lib和头文件都是同一个版本，报下面的问题。

Thread 5 "hqtrade_bin" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeffff700 (LWP 152306)]
__strncpy_avx2 () at ../sysdeps/x86_64/multiarch/strcpy-avx2.S:301
301     ../sysdeps/x86_64/multiarch/strcpy-avx2.S: No such file or directory.
(gdb)

**Comment by kkqy** [comment]
我跟你一样 也是 SubscribeMarketData  崩溃
