### ISSUE TITLE
请问6.6.1_P1_20210406里面的mac的dylib是自己编译的不？看到上期CTP官网只有linux和windowsde 。

### ISSUE THREAD

**Issue by cheungchingli** [krenx1983/openctp#3]
请问6.6.1_P1_20210406里面的mac的dylib是自己编译的不？看到上期CTP官网只有linux和windowsde 。
刚接触，不甚了解，请见谅。

**Comment by krenx1983** [comment]
是的，Mac版的是我们自己编译的，FreeBSD版也是

**Comment by Anniywell** [comment]
> 请问6.6.1_P1_20210406里面的mac的dylib是自己编译的不？看到上期CTP官网只有linux和windowsde 。 刚接触，不甚了解，请见谅。

这个与上期的CTP的不一样的，只是做到了接口兼容，代码和协议都是不一样的，上期只提供了linux和windows的库

**Comment by cheungchingli** [comment]
谢谢回复。
