### ISSUE TITLE
为何一秒内两个tick的时间一样？缺毫秒部分。有时两个tick成交量一样

### ISSUE THREAD

**Issue by qtbgo** [krenx1983/openctp#9]
您好，我使用openctp api，打印了tick时间，价格，成交量信息，如下
bee tick time ag2206.SHFE 2022-04-29 10:54:24 4944.0 322397 
bee tick time ag2206.SHFE 2022-04-29 10:54:25 4943.0 322400 
bee tick time ag2206.SHFE 2022-04-29 10:54:25 4943.0 322400 
bee tick time ag2206.SHFE 2022-04-29 10:54:26 4943.0 322468 
bee tick time ag2206.SHFE 2022-04-29 10:54:26 4943.0 322471
发现两个问题;
1 一秒内两个tick的时间一样，缺毫秒部分。比如2022-04-29 10:54:25的两个tick。好像simnow里的tick不会出现这种现象。
2 有时1秒内的两个tick累积成交量一样，比如2022-04-29 10:54:25的两个tick，我理解其中第二个tick是0.5秒处的tick，其累积成交量应该变大。
any idea？

**Comment by xingyuuchen** [comment]
请问你当时接的是哪个柜台？
